"use strict";
exports.__esModule = true;
var myString;
var myNum;
var myBool;
var myVar;
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = "Hello world";
myNum = 22;
myBool = true;
myVar = "Anything";
boolArr = [true, false];
strArr = ["Hello", "World"];
numArr = [1, 2, 3];
strNumTuple = ["hello", 7];
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
console.log(strArr);
